# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-10 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='balancesheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documentid', models.IntegerField(default=0)),
                ('glcode', models.IntegerField(default=0)),
                ('gldescription', models.CharField(max_length=30)),
                ('amount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='profitandloss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documentid', models.IntegerField(default=0)),
                ('glcode', models.IntegerField(default=0)),
                ('gldescription', models.CharField(max_length=30)),
                ('amount', models.IntegerField(default=0)),
            ],
        ),
    ]
