# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-11 14:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyNetPercentage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(choices=[('United States', 'United States'), ('Aus, NZ & Canada', 'Aus, NZ & Canada'), ('Europe', 'Europe'), ('Emerging Markets', 'Emerging Markets'), ('Japan', 'Japan')], max_length=25)),
                ('industry', models.CharField(choices=[('Advertising', 'Advertising'), ('aerospace', 'aerospace'), ('air transport', 'air transport'), ('apparel', 'apparel')], max_length=25)),
                ('npy2015', models.FloatField()),
                ('npy2016', models.FloatField()),
                ('npy2017', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry_name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='npmargin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('npy2015', models.IntegerField(default=0)),
                ('npy2016', models.IntegerField(default=0)),
                ('npy2017', models.IntegerField(default=0)),
                ('industry', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='operating.Industry')),
            ],
        ),
        migrations.CreateModel(
            name='operatingmargin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opy2015', models.IntegerField(default=0)),
                ('opy2016', models.IntegerField(default=0)),
                ('opy2017', models.IntegerField(default=0)),
                ('industry', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='operating.Industry')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='operatingmargin',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='operating.Region'),
        ),
        migrations.AddField(
            model_name='npmargin',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='operating.Region'),
        ),
    ]
