# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-12 01:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operating', '0002_companynetpercentage_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companynetpercentage',
            name='user',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
