# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-16 03:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operating', '0003_auto_20180212_0528'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=25)),
            ],
        ),
        migrations.AlterField(
            model_name='companynetpercentage',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='operating.User'),
        ),
    ]
