# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-16 03:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operating', '0004_auto_20180216_0754'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserName',
        ),
    ]
