# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-16 04:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operating', '0005_auto_20180216_0758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companynetpercentage',
            name='npy2015',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='companynetpercentage',
            name='npy2016',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='companynetpercentage',
            name='npy2017',
            field=models.IntegerField(default=0),
        ),
    ]
