# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-03 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operating', '0007_auto_20180216_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='npmargin',
            name='npy2015',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='npmargin',
            name='npy2016',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='npmargin',
            name='npy2017',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
