# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-09 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operating', '0008_auto_20180303_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companynetpercentage',
            name='industry',
            field=models.CharField(choices=[('Advertising', 'Advertising'), ('aerospace', 'aerospace'), ('air transport', 'air transport'), ('apparel', 'apparel'), ('Auto & Truck', 'Auto & Truck'), ('Auto Parts', 'Auto Parts'), ('Utility (Water)', 'Utility (Water)'), ('Utility (General)', 'Utility (General)'), ('Trucking', 'Trucking'), ('Transportation (Railroads)', 'Transportation (Railroads)'), ('Transportation', 'Transportation'), ('Tobacco', 'Tobacco'), ('Telecom. Services', 'Telecom. Services'), ('Telecom. Equipment', 'Telecom. Equipment'), ('Telecom (Wireless)', 'Telecom (Wireless)')], max_length=25),
        ),
    ]
