# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-12 00:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operating', '0009_auto_20180309_1246'),
    ]

    operations = [
        migrations.CreateModel(
            name='trialbalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('glcode', models.IntegerField(default=0)),
                ('gldescription', models.CharField(max_length=30)),
                ('classification', models.CharField(max_length=30)),
                ('subclassification', models.CharField(max_length=30)),
                ('debit_cy', models.IntegerField(default=0)),
                ('credit_cy', models.IntegerField(default=0)),
                ('debit_py', models.IntegerField(default=0)),
                ('credit_py', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='companynetpercentage',
            name='industry',
            field=models.CharField(choices=[('Advertising', 'Advertising'), ('aerospace', 'aerospace'), ('air transport', 'air transport'), ('apparel', 'apparel'), ('Auto & Truck', 'Auto & Truck'), ('Auto Parts', 'Auto Parts'), ('Utility (Water)', 'Utility (Water)'), ('Utility (General)', 'Utility (General)'), ('Trucking', 'Trucking'), ('Transportation (Railroads)', 'Transportation (Railroads)'), ('Transportation', 'Transportation'), ('Tobacco', 'Tobacco'), ('Telecom. Services', 'Telecom. Services'), ('Telecom. Equipment', 'Telecom. Equipment'), ('Telecom (Wireless)', 'Telecom (Wireless)'), ('Steel', 'Steel'), ('Software (System & Application)', 'Software (System & Application)'), ('Software (Internet)', 'Software (Internet)'), ('Software (Entertainment)', 'Software (Entertainment)'), ('Shoe', 'Shoe'), ('Shipbuilding & Marine', 'Shipbuilding & Marine'), ('Semiconductor Equip', 'Semiconductor Equip')], max_length=25),
        ),
    ]
