# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-17 11:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('operating', '0011_remove_trialbalance_gldescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='trialbalance',
            name='gldescription',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
    ]
