# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-22 05:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operating', '0013_auto_20180321_0728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trialbalance',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='trialbalance',
            name='region',
        ),
        migrations.RemoveField(
            model_name='trialbalance',
            name='user',
        ),
    ]
