# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-22 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operating', '0014_auto_20180322_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='trialbalance',
            name='industry',
            field=models.CharField(choices=[('Advertising', 'Advertising'), ('aerospace', 'aerospace'), ('air transport', 'air transport'), ('apparel', 'apparel'), ('Auto & Truck', 'Auto & Truck'), ('Auto Parts', 'Auto Parts'), ('Utility (Water)', 'Utility (Water)'), ('Utility (General)', 'Utility (General)'), ('Trucking', 'Trucking'), ('Transportation (Railroads)', 'Transportation (Railroads)'), ('Transportation', 'Transportation'), ('Tobacco', 'Tobacco'), ('Telecom. Services', 'Telecom. Services'), ('Telecom. Equipment', 'Telecom. Equipment'), ('Telecom (Wireless)', 'Telecom (Wireless)'), ('Steel', 'Steel'), ('Software (System & Application)', 'Software (System & Application)'), ('Software (Internet)', 'Software (Internet)'), ('Software (Entertainment)', 'Software (Entertainment)'), ('Shoe', 'Shoe'), ('Shipbuilding & Marine', 'Shipbuilding & Marine'), ('Semiconductor Equip', 'Semiconductor Equip')], default=0, max_length=25),
        ),
        migrations.AddField(
            model_name='trialbalance',
            name='region',
            field=models.CharField(choices=[('United States', 'United States'), ('Aus, NZ & Canada', 'Aus, NZ & Canada'), ('Europe', 'Europe'), ('Emerging Markets', 'Emerging Markets'), ('Japan', 'Japan')], default=0, max_length=25),
        ),
        migrations.AddField(
            model_name='trialbalance',
            name='user',
            field=models.CharField(default=0, max_length=25),
        ),
    ]
