# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-23 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operating', '0015_auto_20180322_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='companynetpercentage',
            name='debtequity_ratio_2016',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='companynetpercentage',
            name='debtequity_ratio_2017',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='companynetpercentage',
            name='gross_profit_margin_2016',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='companynetpercentage',
            name='gross_profit_margin_2017',
            field=models.IntegerField(default=0),
        ),
    ]
