# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-23 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operating', '0017_auto_20180323_2016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companynetpercentage',
            old_name='npy2015',
            new_name='debtequity_ratio_2015',
        ),
        migrations.RenameField(
            model_name='companynetpercentage',
            old_name='npy2016',
            new_name='gross_profit_margin_2015',
        ),
        migrations.RemoveField(
            model_name='companynetpercentage',
            name='npy2017',
        ),
        migrations.AddField(
            model_name='companynetpercentage',
            name='netmargin_percentage_2015',
            field=models.DecimalField(decimal_places=2, default=4, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companynetpercentage',
            name='netmargin_percentage_2016',
            field=models.DecimalField(decimal_places=2, default=4, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companynetpercentage',
            name='netmargin_percentage_2017',
            field=models.DecimalField(decimal_places=2, default=4, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='companynetpercentage',
            name='industry',
            field=models.CharField(choices=[('Advertising', 'Advertising'), ('aerospace', 'aerospace'), ('air transport', 'air transport'), ('apparel', 'apparel'), ('Auto & Truck', 'Auto & Truck'), ('Auto Parts', 'Auto Parts'), ('Utility (Water)', 'Utility (Water)'), ('Utility (General)', 'Utility (General)'), ('Trucking', 'Trucking'), ('Transportation (Railroads)', 'Transportation (Railroads)'), ('Transportation', 'Transportation'), ('Tobacco', 'Tobacco'), ('Telecom. Services', 'Telecom. Services'), ('Telecom. Equipment', 'Telecom. Equipment'), ('Telecom (Wireless)', 'Telecom (Wireless)'), ('Steel', 'Steel'), ('Software (System & Application)', 'Software (System & Application)'), ('Software (Internet)', 'Software (Internet)'), ('Software (Entertainment)', 'Software (Entertainment)'), ('Shoe', 'Shoe'), ('Shipbuilding & Marine', 'Shipbuilding & Marine'), ('Semiconductor Equip', 'Semiconductor Equip'), ('Semiconductor', 'Semiconductor'), ('Rubber& Tires', 'Rubber& Tires'), ('Retail (Special Lines)', 'Retail (Special Lines)'), ('Retail (Online)', 'Retail (Online)'), ('Retail (Grocery and Food)', 'Retail (Grocery and Food)'), ('Retail (General)', 'Retail (General)'), ('Retail (Distributors)', 'Retail (Distributors)'), ('Retail (Building Supply)', 'Retail (Building Supply)'), ('Retail (Automotive)', 'Retail (Automotive)'), ('Restaurant/Dining', 'Restaurant/Dining'), ('Reinsurance', 'Reinsurance'), ('Recreation', 'Recreation')], max_length=25),
        ),
        migrations.AlterField(
            model_name='trialbalance',
            name='industry',
            field=models.CharField(choices=[('Advertising', 'Advertising'), ('aerospace', 'aerospace'), ('air transport', 'air transport'), ('apparel', 'apparel'), ('Auto & Truck', 'Auto & Truck'), ('Auto Parts', 'Auto Parts'), ('Utility (Water)', 'Utility (Water)'), ('Utility (General)', 'Utility (General)'), ('Trucking', 'Trucking'), ('Transportation (Railroads)', 'Transportation (Railroads)'), ('Transportation', 'Transportation'), ('Tobacco', 'Tobacco'), ('Telecom. Services', 'Telecom. Services'), ('Telecom. Equipment', 'Telecom. Equipment'), ('Telecom (Wireless)', 'Telecom (Wireless)'), ('Steel', 'Steel'), ('Software (System & Application)', 'Software (System & Application)'), ('Software (Internet)', 'Software (Internet)'), ('Software (Entertainment)', 'Software (Entertainment)'), ('Shoe', 'Shoe'), ('Shipbuilding & Marine', 'Shipbuilding & Marine'), ('Semiconductor Equip', 'Semiconductor Equip'), ('Semiconductor', 'Semiconductor'), ('Rubber& Tires', 'Rubber& Tires'), ('Retail (Special Lines)', 'Retail (Special Lines)'), ('Retail (Online)', 'Retail (Online)'), ('Retail (Grocery and Food)', 'Retail (Grocery and Food)'), ('Retail (General)', 'Retail (General)'), ('Retail (Distributors)', 'Retail (Distributors)'), ('Retail (Building Supply)', 'Retail (Building Supply)'), ('Retail (Automotive)', 'Retail (Automotive)'), ('Restaurant/Dining', 'Restaurant/Dining'), ('Reinsurance', 'Reinsurance'), ('Recreation', 'Recreation')], default=0, max_length=25),
        ),
    ]
