# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-23 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operating', '0018_auto_20180323_2024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operatingmargin',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='operatingmargin',
            name='region',
        ),
        migrations.RenameField(
            model_name='trialbalance',
            old_name='credit_cy',
            new_name='credit_2015',
        ),
        migrations.RenameField(
            model_name='trialbalance',
            old_name='credit_py',
            new_name='credit_2016',
        ),
        migrations.RenameField(
            model_name='trialbalance',
            old_name='debit_cy',
            new_name='credit_2017',
        ),
        migrations.RenameField(
            model_name='trialbalance',
            old_name='debit_py',
            new_name='debit_2015',
        ),
        migrations.AddField(
            model_name='trialbalance',
            name='debit_2016',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trialbalance',
            name='debit_2017',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='operatingmargin',
        ),
    ]
