# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-25 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operating', '0020_auto_20180324_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='npmargin',
            name='debtequity_ratio_2015',
            field=models.DecimalField(decimal_places=2, default=4, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='npmargin',
            name='debtequity_ratio_2016',
            field=models.DecimalField(decimal_places=2, default=4, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='npmargin',
            name='debtequity_ratio_2017',
            field=models.DecimalField(decimal_places=2, default=4, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='npmargin',
            name='gross_profit_margin_2015',
            field=models.DecimalField(decimal_places=2, default=4, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='npmargin',
            name='gross_profit_margin_2016',
            field=models.DecimalField(decimal_places=2, default=4, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='npmargin',
            name='gross_profit_margin_2017',
            field=models.DecimalField(decimal_places=2, default=4, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trialbalance',
            name='gldescription',
            field=models.CharField(max_length=60),
        ),
    ]
